---
  - name: Create TLS directory
    file:
      path: "{{ consul_tls_dir }}"
      state: directory
      owner: "{{ consul_user }}"
      group: "{{ consul_group }}"
      mode: "0750"
  - name     : generate server cert
    uri      :
      url            : "{{vault_addr}}/v1/{{vault_pki_mount}}/issue/{{vault_pki_role}}"
      return_content : true
      method         : POST
      headers        :
        X-Vault-Token     : "{{vault_token}}"
        X-Vault-Namespace : "{{vault_namespace}}"
      body           :
        common_name : server.{{data_center}}.{{consul_domain}}
        ttl         : "{{cert_ttl}}"
      body_format    : json
    register : vault_cert_output

  - name: load cert (doesn't log output)
    copy:
      content: "{{item.cert}}"
      dest   : "{{item.location}}"
    no_log: true
    with_items: 
      - cert: "{{vault_cert_output.json.data.issuing_ca}}"
        location: "{{consul_tls_dir}}/consul-agent-ca.pem"
      - cert: "{{vault_cert_output.json.data.private_key}}"
        location: "{{consul_tls_dir}}/dc1-client-consul-0-key.pem"
      - cert: "{{vault_cert_output.json.data.certificate}}"
        location: "{{consul_tls_dir}}/dc1-client-consul-0.pem"
    notify: Restart Consul
