---

  - name: Create vault Directory
    file:
      path: "{{item}}"
      state: directory
      owner: consul
      group: consul
      mode: "0750"
    with_items: 
      - "/etc/consul.d/token"

  - name: Add Consul Client config
    template:
      src: client-config.hcl.j2
      dest: "{{consul_config_dir}}/client-config.hcl"

  - name: Add bootstrap script
    template:
      src: 5-consul-bootstrap.sh.j2
      dest: "/var/lib/cloud/scripts/per-boot/5-consul-bootstrap.sh"
      mode: "0777"