---

  - name: Create TLS directory
    file:
      path: "{{ consul_tls_dir }}"
      state: directory
      owner: "{{ consul_user }}"
      group: "{{ consul_group }}"
      mode: "0750"
  
  - name: Initialize the built-in CA
    command:
      cmd: consul tls ca create
      creates: consul-agent-ca-key.pem
      chdir: "{{ consul_tls_dir }}"
    run_once: true
  
  - name: Generating server certificates
    command:
      cmd: consul tls cert create -server 
      creates: dc1-server-consul-0-key.pem
      chdir: "{{ consul_tls_dir }}"
    run_once: true
  
  - name: Change dc1-server-consul-0-key.pem permission
    file:
      path: "{{ consul_tls_dir }}/dc1-server-consul-0-key.pem"
      group: consul
      mode: "0640"
    run_once: true
  
  - name: Archive the tls directory
    archive:
      path: "{{ consul_tls_dir }}"
      dest: "{{consul_config_dir}}/tls.tgz"
      mode: "0600"
    run_once: true
  
  - name: Register tls directory
    command:
      cmd: cat {{consul_config_dir}}/tls.tgz
    register: TLS
    run_once: true
  
  - name: Load TLS into every Consul Server
    copy:
      dest: "{{consul_config_dir}}/tls.tgz"
      content: "{{ TLS.stdout }}"
      mode: "0600"
    when: ("consul_servers" in group_names)
  
  - name: Unzip the TLS directory
    unarchive:
      src: "{{consul_config_dir}}/tls.tgz"
      dest: "{{ consul_config_dir }}"
      remote_src: true
      creates: "{{consul_tls_dir}}/dc1-server-consul-0-key.pem"
    when: ("consul_servers" in group_names)
    notify: Restart Consul
  
  - name: Generating client certificates
    command:
      cmd: consul tls cert create -client 
      creates: dc1-client-consul-0-key.pem
      chdir: "{{ consul_tls_dir }}"
    run_once: true
  
  - name: Change dc1-client-consul-0-key.pem permission
    file:
      path: "{{consul_tls_dir}}/dc1-client-consul-0-key.pem"
      group: consul
      mode: "0640"
    run_once: true
  
  - name: Archive the tls directory for client
    archive:
      path: 
        - "{{consul_tls_dir}}/dc1-client-consul-0.pem"
        - "{{consul_tls_dir}}/dc1-client-consul-0-key.pem"
        - "{{consul_tls_dir}}/consul-agent-ca.pem"
      dest: "{{consul_config_dir}}/tls-client.tgz"
      mode: "0600"
    run_once: true
  
  - name: Register tls directory
    command:
      cmd: cat {{consul_config_dir}}/tls-client.tgz
    register: CLIENTTLS
    run_once: true
  
  - name: Load TLS into every Consul Client
    copy:
      dest: "{{consul_config_dir}}/tls-client.tgz"
      content: "{{ CLIENTTLS.stdout }}"
      mode: "0600"
    when: ("consul_client" in group_names)
  
  - name: Unzip the TLS-CLIENT directory
    unarchive:
      src: "{{consul_config_dir}}/tls-client.tgz"
      dest: "{{ consul_tls_dir }}"
      remote_src: true
      creates: "{{consul_tls_dir}}/dc1-client-consul-0-key.pem"
    when: ("consul_client" in group_names)
    notify: Restart Consul