---

- name: Restart Consul
  systemd:
    name: consul.service
    state: restarted
    enabled: true
    daemon_reload: true
  when: not packer_build

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
    enabled: true
